(() => {
  'use strict';
  const market = createSalesBench();
  // Binding is chosen by the trusted local host, never from the Agent JSON payload.
  const buyer = market.bindBuyer('buyer_001');
  const $ = id=>document.getElementById(id);
  const escape = value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const amount = cents=>(cents/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
  const price = cents=>(cents/100).toLocaleString('zh-CN',{maximumFractionDigits:2});
  const paths={rank:'<path d="M4 20v-7h4v7M10 20V5h4v15M16 20V9h4v11"/>',products:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',public:'<path d="M20 11.5a8 8 0 0 1-8 7.5H7l-4 3 1-5A8 8 0 1 1 20 11.5Z"/><path d="M8 10h8M8 14h5"/>',private:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="m4 7 8 6 8-6"/>',me:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',wallet:'<path d="M20 8H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h13v5M3 6v13a2 2 0 0 0 2 2h15V8M16 12h5v5h-5a2.5 2.5 0 0 1 0-5Z"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7v1"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',store:'<path d="m3 8 2-5h14l2 5v3H3V8Zm2 3v10h14V11M9 21v-6h6v6M7 3l-1 5m6-5v5m5-5 1 5"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',check:'<path d="m5 12 4 4L19 6"/>',bag:'<path d="M5 7h14l1 14H4L5 7Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/>',shield:'<path d="m12 3 8 3v5c0 5-4 8-8 10-4-2-8-5-8-10V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',send:'<path d="m3 3 18 9-18 9 3-9-3-9Zm3 9h15"/>'};
  const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true" stroke-linecap="round" stroke-linejoin="round">${paths[name]||paths.info}</svg>`;
  const pages=[['leaderboard','排行榜','rank'],['products','商品推荐','products'],['public','公共交流','public'],['private','私聊','private'],['me','我的','me']];
  let current, dialogState=null, counter=0, toastTimer, draft={};
  const doAction=(type,payload={})=>buyer.execute({id:`ui-${Date.now()}-${++counter}`,type,payload});
  const avatar=m=>`<span class="merchant-avatar ${m.color}">${escape(m.initial)}</span>`;
  const merchant=id=>current.merchants.find(m=>m.id===id);
  const button=(text,action,attr='',cls='btn')=>`<button type="button" class="${cls}" data-action="${action}" ${attr}>${text}</button>`;
  const go=(page,mid)=>{closeModal(false);doAction('browse',{page,...(mid?{merchantId:mid}:{})});};
  function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
  function header(title,subtitle){return `<div class="page-head"><div><div class="eyebrow">买方体验 / 演示场次 01</div><h1>${title}</h1><p>${subtitle}</p></div>${button(icon('info')+'演示说明','config','','quiet-button')}</div>`;}
  function notice(text){return `<div class="notice">${icon('info')}<span>${text}</span></div>`;}
  function rankPage(){
    const rows=current.leaderboard;
    return header('看看商家们的表现','浏览排名，发现商品，也可以先聊聊再决定。')+notice('演示榜单 · 按模拟累计成交额排序，含预置数据；购买后同步更新。')+
    `<div class="standings">${[rows[1],rows[0],rows[2]].map(m=>`<article class="standing ${m.rank===1?'first':''}"><span class="position">0${m.rank}</span>${m.rank===1?'<div class="medal-label">当前领先</div><br>':''}${avatar(m)}<h3>${m.name}</h3><div class="subline">${m.tag}</div><div class="rank-label">模拟累计成交额</div><div class="money">¥ ${amount(m.revenueCents)}</div><div class="subline">已成交 ${m.sold} 件</div>${button('逛逛这家 '+icon('arrow'),'browse',`data-page="products" data-merchant="${m.id}"`,m.rank===1?'btn primary':'btn')}</article>`).join('')}</div>
    <div class="section-title"><h2>商家一览</h2><span>3 家商家 · 排名向买家公开</span></div><div class="panel table-wrap"><table><thead><tr><th>排名</th><th>商家</th><th>模拟成交额</th><th>成交件数</th><th>了解商家</th></tr></thead><tbody>${rows.map(m=>`<tr><td><span class="rank-num">0${m.rank}</span></td><td><div class="seller-cell">${avatar(m)}<div><strong>${m.name}</strong><small>${m.tag}</small></div></div></td><td><strong>¥ ${amount(m.revenueCents)}</strong></td><td>${m.sold} 件</td><td><div class="row-actions">${button('公开交流','browse',`data-page="public" data-merchant="${m.id}"`,'text-btn')}${button('私聊商家','browse',`data-page="private" data-merchant="${m.id}"`,'text-btn')}</div></td></tr>`).join('')}</tbody></table></div>
    <div class="rank-footer"><span>排名只代表当前演示成交情况。按自己的需要选择，随时可以不购买。</span>${button('浏览全部商品 '+icon('arrow'),'browse','data-page="products"','btn soft')}</div>`;
  }
  function productCard(p){const m=merchant(p.merchantId);return `<article class="panel product-card"><button class="product-picture" type="button" data-action="detail" data-product="${p.id}" aria-label="查看${p.name}详情"><img src="${p.image}" alt="${p.name}商品示意图"><span class="photo-tag">商品示意</span></button><div class="product-info"><button type="button" class="merchant-link" data-action="browse" data-page="public" data-merchant="${m.id}">${icon('store')}${m.name}</button><h3>${p.name}</h3><div class="variant">${p.variant}</div><div class="product-buy"><div><div class="price"><i>¥</i>${price(p.priceCents)}</div><div class="stock">剩余 ${p.stock} 件</div></div>${button(p.stock?'直接购买':'已售罄','checkout',`data-product="${p.id}" ${p.stock?'':'disabled'}`,'btn soft')}</div></div></article>`;}
  function productsPage(){const filter=current.navigation.filterMerchantId;return header('发现适合你的好物','先看看商品，再选择交流或直接购买。')+notice('演示推荐 · 以下为固定展示顺序，未启用个性化推荐。')+`<div class="filters" aria-label="按商家浏览">${button('全部商家','browse','data-page="products"',`chip ${!filter?'active':''}`)}${current.merchants.map(m=>button(m.name,'browse',`data-page="products" data-merchant="${m.id}"`,`chip ${filter===m.id?'active':''}`)).join('')}</div><div class="product-grid">${current.products.filter(p=>!filter||p.merchantId===filter).map(productCard).join('')}</div>`;}
  function messageHTML(msg){const own=msg.authorId===current.actor.id;const m=current.merchants.find(m=>m.name===msg.authorName);return `<div class="message ${own?'self':''} ${msg.role==='merchant'?'merchant-message':''}">${m?avatar(m):`<span class="message-avatar">${own?'我':escape(msg.authorName.slice(0,1))}</span>`}<div><div class="message-meta"><span>${escape(msg.authorName)}</span>${msg.role==='merchant'?'<span class="preset-tag">商家 · 预设回复</span>':msg.preset?'<span class="preset-tag">演示买家</span>':''}<time>${escape(msg.time)}</time></div><div class="message-bubble">${escape(msg.text)}</div></div></div>`;}
  function chatPage(isPrivate){const m=merchant(current.merchantId),p=current.products.find(p=>p.id===m.featuredProductId)||current.products[0];const key=`${current.view}:${m.id}`;return header(isPrivate?'和商家单独聊聊':'一起聊聊，了解更多',isPrivate?'这里的消息仅在你与当前商家的会话中可见。':'每个商家一个讨论区，问题与回复向本场买家公开。')+`<div class="panel chat-layout"><aside class="chat-list"><div class="chat-list-title">${isPrivate?'商家会话':'商家讨论区'}</div>${current.merchants.map(s=>{const last=isPrivate?current.conversations.find(c=>c.merchantId===s.id)?.lastMessage.text:s.description;return `<button type="button" class="contact ${s.id===m.id?'selected':''}" data-action="browse" data-page="${isPrivate?'private':'public'}" data-merchant="${s.id}" aria-label="${s.name}${isPrivate?'私聊':'讨论区'}">${avatar(s)}<span class="contact-copy"><strong>${s.name}</strong><small>${escape(last)}</small></span></button>`;}).join('')}</aside><section class="chat-right"><div class="conversation-head"><div><strong>${m.name}${isPrivate?'':' · 讨论区'}</strong><p>${isPrivate?'私密会话 · 商家回复为演示预设':'公开交流 · 本场买家均可参与'}</p></div>${button(isPrivate?'去公开交流':'私聊商家','browse',`data-page="${isPrivate?'public':'private'}" data-merchant="${m.id}"`,'btn small')}</div>${isPrivate?`<div class="private-product-strip"><img src="${p.image}" alt="${p.name}"><span>${p.name} <b>¥${price(p.priceCents)}</b></span>${button('查看商品','detail',`data-product="${p.id}"`,'text-btn')}</div>`:`<div class="sales-description"><div class="sales-copy"><div class="tiny">${icon('store')} 商家销售描述</div><p>${m.pitch}</p></div><div class="feature-product"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><div class="price"><i>¥</i>${price(p.priceCents)}</div>${button('查看商品 →','detail',`data-product="${p.id}"`,'text-btn')}</div></div></div>`}<div class="messages" role="log" aria-label="${isPrivate?'私聊消息':'公开消息'}">${current.messages.map(messageHTML).join('')}</div><form class="composer" id="message-form"><label for="message-input">${isPrivate?'发送给 '+m.name+' · 仅当前会话可见':'发送至 '+m.name+'讨论区 · 公开可见'}（最多 500 字）</label><div class="composer-row"><textarea id="message-input" name="message" maxlength="500" rows="1" placeholder="${isPrivate?'想了解什么？直接问问商家…':'有想问的，和大家一起聊聊…'}" aria-label="${isPrivate?'私聊消息内容':'公开消息内容'}">${escape(draft[key]||'')}</textarea><button class="btn primary" type="submit">发送 ${icon('send')}</button></div></form></section></div>`;}
  function mePage(){return header('我的购买与余额','每一次选择，都可以在这里回看。')+`<div class="account-grid"><section class="wallet"><div class="eyebrow">当前可用余额</div>${icon('wallet')}<div class="balance"><span>¥ </span>${amount(current.actor.balanceCents)}</div><p>初始模拟余额 ¥${amount(current.account.initialBalanceCents)} · 无真实资金</p></section><section class="stat-card"><div class="label">累计模拟支出</div><div class="stat">¥${amount(current.account.spentCents)}</div><div class="tiny">本次会话已完成的购买</div></section><section class="stat-card"><div class="label">购买记录</div><div class="stat">${current.orders.length} <span style="font-size:16px;font-weight:400">笔</span></div><div class="tiny">共 ${current.orders.reduce((n,o)=>n+o.quantity,0)} 件商品</div></section></div><section class="panel history"><div class="history-head"><h2>购买历史</h2>${button('继续浏览 '+icon('arrow'),'browse','data-page="products"','btn small')}</div>${current.orders.length?`<div class="table-wrap"><table><thead><tr><th>商品 / 商家</th><th>数量</th><th>金额</th><th>状态</th><th>购买时间</th></tr></thead><tbody>${current.orders.map(o=>`<tr><td class="order-product">${escape(o.productName)}<small>${escape(o.merchantName)} · ${o.id}</small></td><td>${o.quantity} 件</td><td><b>¥${amount(o.totalCents)}</b></td><td><span class="order-status">${o.status}</span></td><td class="muted">${new Date(o.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty-state">${icon('bag')}<h3>还没有购买记录</h3><p>可以先浏览、聊聊，等找到需要的再购买。</p>${button('去看看商品','browse','data-page="products"','btn primary')}</div>`}</section><p class="account-note">${icon('info')}所有购买均为模拟操作；刷新或重新打开页面会重置本次会话。</p>`;}
  function render(){current=buyer.observe();const page=current.view;const pageName=pages.find(p=>p[0]===page)[1];$('app').innerHTML=`<aside class="sidebar"><div class="brand"><span class="brand-icon">${icon('rank')}</span><span class="brand-name">SalesBench</span></div><div class="brand-sub">买 方 体 验</div><nav class="nav" aria-label="主导航">${pages.map(([key,name,ic])=>`<button type="button" data-action="browse" data-page="${key}" class="${key===page?'active':''}" ${key===page?'aria-current="page"':''}>${icon(ic)}<span>${name}</span></button>`).join('')}</nav><div class="side-foot"><span class="demo-badge">演示环境 · V1</span><p>模拟商品与商家<br>自由浏览，自主选择</p></div></aside><div class="main"><header class="topbar"><div class="breadcrumb">买方空间 <span>/</span> <strong>${pageName}</strong></div><div class="mobile-brand">${icon('rank')}SalesBench</div><div class="userbar"><span class="balance-pill">${icon('wallet')} 模拟余额 <b>¥ ${amount(current.actor.balanceCents)}</b></span><span class="user-chip"><span class="user-avatar">我</span><span>体验买家 <span class="muted tiny">#001</span></span></span></div></header><main class="content">${page==='leaderboard'?rankPage():page==='products'?productsPage():page==='public'?chatPage(false):page==='private'?chatPage(true):mePage()}</main></div>`;
    const input=$('message-input');if(input)input.addEventListener('input',()=>draft[`${current.view}:${current.merchantId}`]=input.value);
    const log=document.querySelector('.messages');if(log)log.scrollTop=log.scrollHeight;
  }
  function closeModal(update=true){if($('modal').open)$('modal').close();dialogState=null;if(update&&buyer.observe().navigation.focusedProductId)doAction('close_detail');}
  function modal(title,body,actions=''){const el=$('modal');el.innerHTML=`<div class="modal-head"><h2 id="modal-title">${title}</h2>${button(icon('close'),'close','aria-label="关闭弹窗"','close-btn')}</div>${body}${actions?`<div class="modal-actions">${actions}</div>`:''}`;el.setAttribute('aria-labelledby','modal-title');if(!el.open)el.showModal();}
  function product(id){return buyer.observe({view:'product',productId:id}).product;}
  function openDetail(id,sync=true){const p=product(id);if(!p)return;dialogState={type:'detail',productId:id};if(sync)doAction('view_product',{productId:id});const m=merchant(p.merchantId);modal('商品详情',`<div class="modal-body"><div class="detail-top"><img src="${p.image}" alt="${p.name}商品示意图"><div><div class="merchant-link">${icon('store')}${m.name}</div><h2>${p.name}</h2><p class="variant">${p.variant}</p><div class="price"><i>¥</i>${price(p.priceCents)}</div><div class="stock">剩余 ${p.stock} 件 · 商品图片为示意</div></div></div><div class="specs">${p.specs.map(s=>`<span>${s}</span>`).join('')}</div><p class="detail-description">${p.description}</p><div class="detail-secondary">${button(icon('public')+'公开交流','browse',`data-page="public" data-merchant="${m.id}"`)}${button(icon('private')+'私聊商家','browse',`data-page="private" data-merchant="${m.id}"`)}</div></div>`,button('暂不购买','decline',`data-product="${id}"`,'text-btn')+button('继续浏览','close')+button('购买此商品','checkout',`data-product="${id}" ${p.stock?'':'disabled'}`,'btn primary'));}
  function checkout(id){const p=product(id);if(!p)return;dialogState={type:'checkout',productId:id,actionId:`purchase-${Date.now()}-${++counter}`,unitPrice:p.priceCents};doAction('view_product',{productId:id});const m=merchant(p.merchantId);modal('确认模拟购买',`<div class="modal-body"><div class="checkout-product"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${m.name} · ${p.variant}</p></div></div><div class="summary-row"><span>单价</span><strong>¥${amount(p.priceCents)}</strong></div><div class="summary-row"><label for="quantity">购买数量 <span class="tiny">（库存 ${p.stock} 件）</span></label><input class="quantity-input" id="quantity" type="number" min="1" max="${Math.min(p.stock,99)}" value="1" step="1"></div><div class="summary-row total"><span>模拟支付</span><strong id="checkout-total">¥${amount(p.priceCents)}</strong></div><div class="summary-row"><span>购买后余额</span><strong id="checkout-balance">¥${amount(current.actor.balanceCents-p.priceCents)}</strong></div><div id="checkout-error" class="field-error" role="alert"></div><p class="dialog-small-note">本次操作只扣减模拟余额，并更新库存及购买历史，不涉及真实付款。</p></div>`,button('暂不购买','decline',`data-product="${id}"`,'text-btn')+button('返回详情','detail',`data-product="${id}"`)+button('确认购买','confirm','','btn primary'));const validate=()=>{const q=Number($('quantity').value);const valid=Number.isInteger(q)&&q>0&&q<=99;const total=valid?p.priceCents*q:0;$('checkout-total').textContent=valid?'¥'+amount(total):'—';$('checkout-balance').textContent=valid?'¥'+amount(current.actor.balanceCents-total):'—';const error=!valid?'请输入 1–99 的整数数量。':q>p.stock?'剩余库存不足，请调整数量。':total>current.actor.balanceCents?'模拟余额不足，可以继续浏览其他商品。':'';$('checkout-error').textContent=error;$('modal').querySelector('[data-action="confirm"]').disabled=!!error;};$('quantity').addEventListener('input',validate);validate();}
  function purchased(receipt){clearTimeout(toastTimer);$('toast').classList.remove('show');dialogState={type:'success'};const o=receipt.result.order;modal('购买完成',`<div class="success-body"><div class="success-check">${icon('check')}</div><h2>已完成模拟购买</h2><p>${escape(o.merchantName)} · ${escape(o.productName)} × ${o.quantity}</p><div class="success-amount">¥${amount(o.totalCents)}</div><p>当前余额 ¥${amount(receipt.result.balanceCents)}<br>购买记录已保存至「我的」</p></div>`,button('继续浏览','browse','data-page="products"')+button('查看购买历史','browse','data-page="me"','btn primary'));}
  function showConfig(){dialogState={type:'config'};const names={ranking:'排行榜',recommendation:'推荐顺序',publicFields:'公开信息',privateFields:'私人信息',replies:'交流与商家回复',session:'会话状态',purchase:'模拟购买'};modal('演示配置说明',`<div class="modal-body"><span class="demo-badge">暂定、可修改 · 非正式实验算法</span><dl class="config-list">${Object.entries(names).map(([key,label])=>`<div><dt>${label}</dt><dd>${escape(current.demoConfig[key])}</dd></div>`).join('')}</dl><p class="dialog-small-note">此版只验证买方操作流程；未接入实验核心、模型或真实支付。</p></div>`,button('知道了','close','','btn primary'));}
  document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action;switch(a){case'browse':go(el.dataset.page,el.dataset.merchant);break;case'detail':openDetail(el.dataset.product);break;case'checkout':checkout(el.dataset.product);break;case'config':showConfig();break;case'close':closeModal();break;case'decline':{const r=doAction('decline_purchase',{productId:el.dataset.product});closeModal(false);toast(r.ok?'已选择暂不购买，余额不变。':r.error.message);break;}case'confirm':{if(!dialogState||dialogState.type!=='checkout')break;el.disabled=true;const state=dialogState;const r=buyer.execute({id:state.actionId,type:'purchase',payload:{productId:state.productId,quantity:Number($('quantity').value),expectedUnitPriceCents:state.unitPrice}});if(r.ok)purchased(r);else{$('checkout-error').textContent=r.error.message;el.disabled=false;}break;}}});
  document.addEventListener('submit',e=>{if(e.target.id!=='message-form')return;e.preventDefault();const key=`${current.view}:${current.merchantId}`;const text=$('message-input').value;const r=doAction(current.view==='public'?'send_public':'send_private',{merchantId:current.merchantId,text});if(r.ok){draft[key]='';render();$('message-input').focus();}else toast(r.error.message);});
  $('modal').addEventListener('cancel',e=>{e.preventDefault();closeModal();});
  $('modal').addEventListener('click',e=>{if(e.target===$('modal')){const box=$('modal').getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)closeModal();}});
  buyer.subscribe(render);
  // Public Agent surface is scoped to exactly this buyer. It cannot export the market or rebind identity.
  const agentAPI=Object.freeze({observe(query={}){return buyer.observe(query);},execute(action){const r=buyer.execute(action);if(r.ok){if(action.type==='view_product'){const p=action.payload.productId;openDetail(p,false);}else if(action.type==='purchase')purchased(r);else closeModal(false);}return r;}});
  Object.defineProperty(window,'salesbench',{value:agentAPI,writable:false,configurable:false});
  if(document.modelContext?.registerTool){for(const tool of [{name:'salesbench_observe',title:'观察当前买方页面',description:'只读取当前买家有权观察的页面数据；不返回其他买家信息或商家内部数据。',inputSchema:{type:'object',properties:{view:{type:'string',enum:['leaderboard','products','public','private','me','product']},merchantId:{type:'string'},productId:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true},execute:q=>agentAPI.observe(q)},{name:'salesbench_execute_action',title:'执行模拟买方动作',description:'执行买方 JSON 动作并返回回执。purchase 会立即扣减模拟余额、减少库存、创建购买记录；无真实付款。',inputSchema:{type:'object',properties:{id:{type:'string'},type:{type:'string',enum:['browse','view_product','close_detail','send_public','send_private','purchase','decline_purchase']},payload:{type:'object'}},required:['id','type','payload'],additionalProperties:false},annotations:{readOnlyHint:false},execute:a=>agentAPI.execute(a)}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
  render();
})();
